---

- name: ファイル名
  debug:
    msg: "これは 'setup-Redhat.yml' です"

- name: ディストリビューション
  debug:
    msg: "{{ ansible_distribution }}"

- name: ディストリビューションのメジャーバージョン
  debug:
    msg: "{{ ansible_distribution_major_version }}"
