---
webservers:
  hosts:
    ayanami:
      ansible_ssh_host: 192.168.33.11
      ansible_ssh_port: 22
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ~/works/vm/eva/.vagrant/machines/ayanami/virtualbox/private_key
    shinji:
      ansible_ssh_host: 192.168.33.12
      ansible_ssh_port: 22
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ~/works/vm/eva/.vagrant/machines/shinji/virtualbox/private_key
    asuka:
      ansible_ssh_host: 192.168.33.13
      ansible_ssh_port: 22
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ~/works/vm/eva/.vagrant/machines/asuka/virtualbox/private_key
