---

webservers:
  hosts:
    ayanami:
      ansible_ssh_host: 192.168.33.11
      ansible_ssh_port: 22
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ~/works/vagrant/eva/.vagrant/machines/ayanami-cen7/virtualbox/private_key
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    shinji:
      ansible_ssh_host: 192.168.33.12
      ansible_ssh_port: 22
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ~/works/vagrant/eva/.vagrant/machines/shinji-deb9/virtualbox/private_key
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
    asuka:
      ansible_ssh_host: 192.168.33.13
      ansible_ssh_port: 22
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ~/works/vagrant/eva/.vagrant/machines/asuka-ubu18/virtualbox/private_key
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
