---
- name: カーネルのバージョンを確認する(skippingならOK)
  fail:
    msg: "Dockerは Kernel {{ ansible_kernel }} をサポートしていません"
  when: "ansible_kernel is version_compare('3.10', '<')"

- include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
